spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: mocroconfig-config-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-dev.com:8077/eureka
---
server:
  port: 8202
spring:
  profiles: beta
  application:
    name: mocroconfig-config-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-beta.com:8077/eureka
---